# my_laptop = input("Enter your laptop brand: ")
# print("My laptop is " + my_laptop)
# print("Nice!!")
# laptop_price = input("My I know the price as well? How much is it? ")
# print("Well, it is around $" + laptop_price)

num_one = input("Enter first number: ")
num_two = input("Enter second number: ")
result = float(num_one) + float(num_two)
print("The result of this addition: " + str(result))